services:
  movie_dinghy_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: movie_dinghy_server
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
